/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helados;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author J_ohn
 */
public class Pantalla extends javax.swing.JFrame {
    SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
    String nombreTamaño ="";
    String nombreTopping="";
    
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        topping = new javax.swing.JPanel();
        cbxchispas = new javax.swing.JCheckBox();
        cbxcajeta = new javax.swing.JCheckBox();
        cbxgomitas = new javax.swing.JCheckBox();
        tamano = new javax.swing.JPanel();
        rbtnsencillo = new javax.swing.JRadioButton();
        rbtndoble = new javax.swing.JRadioButton();
        rbtnjumbo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtiva = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        btnticket = new javax.swing.JButton();
        defecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Helados Jonathan");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/helados/img/if_10_1517190.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(245, 245, 245))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 672, -1));

        topping.setBorder(javax.swing.BorderFactory.createTitledBorder("Topping"));

        cbxchispas.setText("Chispas $5");

        cbxcajeta.setText("Cajeta$10");

        cbxgomitas.setText("Gomitas$15");
        cbxgomitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxgomitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppingLayout = new javax.swing.GroupLayout(topping);
        topping.setLayout(toppingLayout);
        toppingLayout.setHorizontalGroup(
            toppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxchispas)
                    .addComponent(cbxcajeta)
                    .addComponent(cbxgomitas))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        toppingLayout.setVerticalGroup(
            toppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxchispas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxcajeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxgomitas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(topping, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 212, -1, 117));

        tamano.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño"));

        buttonGroup1.add(rbtnsencillo);
        rbtnsencillo.setText("Sencillo $20");
        rbtnsencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnsencilloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtndoble);
        rbtndoble.setText("Doble $30");

        buttonGroup1.add(rbtnjumbo);
        rbtnjumbo.setText("jumbo  $45");

        javax.swing.GroupLayout tamanoLayout = new javax.swing.GroupLayout(tamano);
        tamano.setLayout(tamanoLayout);
        tamanoLayout.setHorizontalGroup(
            tamanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamanoLayout.createSequentialGroup()
                .addGroup(tamanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnsencillo)
                    .addComponent(rbtndoble)
                    .addComponent(rbtnjumbo))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        tamanoLayout.setVerticalGroup(
            tamanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamanoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rbtnsencillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtndoble, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnjumbo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 212, -1, -1));

        txtiva.setEditable(false);

        txttotal.setEditable(false);

        jLabel4.setText("Total");

        txtsubtotal.setEditable(false);

        jLabel2.setText("Subtotal");

        jLabel3.setText("IVA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtsubtotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtiva)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 219, -1, -1));

        jButton1.setText("Suma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 368, -1, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 368, -1, -1));

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 368, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 158, -1, -1));

        jButton4.setText("Mostrar Fecha");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 368, -1, -1));

        btnticket.setText("Ticket");
        btnticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnticketActionPerformed(evt);
            }
        });
        getContentPane().add(btnticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 368, -1, -1));
        getContentPane().add(defecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 147, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnsencilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnsencilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnsencilloActionPerformed

    private void cbxgomitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxgomitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxgomitasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
double subtotal =0.0;
double total= 0.0;
double ivaSub=0.0;
final double IVA = 0.16;

if (rbtnsencillo.isSelected()){
subtotal=subtotal+20;
nombreTamaño=rbtnsencillo.getText();
}else
if (rbtndoble.isSelected()){
subtotal=subtotal+30;
nombreTamaño=rbtndoble.getText();
}else
if (rbtnjumbo.isSelected()){
subtotal=subtotal+45;
nombreTamaño=rbtnjumbo.getText();
}
if(cbxchispas.isSelected()){
    subtotal +=5;
    nombreTopping=cbxchispas.getText();

}
if(cbxcajeta.isSelected()){
    subtotal +=10;
    nombreTopping=cbxcajeta.getText();

}
if(cbxgomitas.isSelected()){
    subtotal +=15;
    nombreTopping=cbxgomitas.getText();

}
ivaSub=subtotal*IVA;
        DecimalFormat dec=new DecimalFormat("#.00");
        dec.format(ivaSub);
total=subtotal + ivaSub;

txtsubtotal.setText(Double.toString(subtotal));
txtiva.setText(Double.toString(ivaSub));
txttotal.setText(Double.toString(total));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,dt.format(defecha.getDate()),"Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnticketActionPerformed
     Ticket t= new Ticket();
     t.setTamaño(nombreTamaño);
     t.setVisible(true);
     t.setTopping(nombreTopping);
     t.setVisible(true);
    }//GEN-LAST:event_btnticketActionPerformed

    /** pantalla
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnticket;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbxcajeta;
    private javax.swing.JCheckBox cbxchispas;
    private javax.swing.JCheckBox cbxgomitas;
    private com.toedter.calendar.JDateChooser defecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbtndoble;
    private javax.swing.JRadioButton rbtnjumbo;
    private javax.swing.JRadioButton rbtnsencillo;
    private javax.swing.JPanel tamano;
    private javax.swing.JPanel topping;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
